import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./component/Footer";
import Nav from "./component/Nav";
import 'swiper/css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Velox",
  description: "Generated by Velox Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  data-theme="light">
      <body className={inter.className}>
        <Nav />
        {children} <Footer />
      </body>
    </html>
  );
}
